version: '3.1'

services:

  baseapp:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    networks:
      - local
    tty: true
    volumes:
      - "./src/app:/var/www/beego/src/app"
    working_dir: /var/www/beego/src/app
    ports:
      - 80:8000

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: godb
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - "/tmp:/tmp"
    networks:
      - local
    ports:
      - 3306:3306

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:8080'
    environment:
      - PMA_ARBITRARY=1
    restart: always
    networks:
      - local

networks:
  local: